### ISSUE TITLE
latest test.js in feedRead repo and npm davefeedread are different

### ISSUE THREAD

**Issue by SparkyT** [scripting/feedRead#1]
Tiny difference but the npm version of test.js shows:
```javascript
const feedReader = require ("davefeedread");
````
whilst this repo shows 
```javascript
const feedRead = require ("davefeedread");
````
(I think the latter is correct)

**Comment by scripting** [comment]
Thanks for the report! ;-)

I just released a new version on NPM, v0.4.7, it has the fix. 

Let me know if it works, or doesn't. :boom:

Dave

**Comment by SparkyT** [comment]
Sorry to report I'm still seeing the following in npm for test.js

![davefeedread047](https://user-images.githubusercontent.com/4244537/38338141-26cad6ce-3860-11e8-8e6d-3a12a87b97c5.PNG)

**Comment by scripting** [comment]
Do you have a *testing* folder? If so, the "real" version of the test app
is in there.

I don't know how to get NPM to delete a file, I think that's the problem.
I've deleted the file in the original folder, but when I re-publish, the
file doesn't get deleted in the public version.

**Comment by SparkyT** [comment]
Ah! Yes - testing\test.js is indeed correct, thanks for explaining.

Tim
